/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Classes.Personaje;
import EstructuraDatos.Cola;
import Extra.RenderImage;
import java.awt.FlowLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author diego
 */
public class ColaUI extends javax.swing.JFrame {

    /**
     * Creates new form ColaUI
     */
    private JPanel queuePanel; // Panel para agregar los JLabel
    private final RenderImage imageUtils = new RenderImage();
    
    public ColaUI() {
        initComponents();
        myInitComponents();
    }
    public ColaUI(String title) {
        initComponents();
        myInitComponents();
        this.titleQueueUI.setText(title);
    }

    private void myInitComponents() {
        queuePanel = new JPanel();
        getQueuePanel().setLayout(new FlowLayout(FlowLayout.LEFT));
        jScrollPaneQueue.setViewportView(getQueuePanel());

        jScrollPaneQueue.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPaneQueue.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

    }

    public void addCard(String urlImage) {
        ImageIcon imgIcon = imageUtils.loadScaledImage(urlImage, 60, 80);
        JLabel etiqueta = new JLabel(imgIcon);
        getQueuePanel().add(etiqueta);
    }

    public void updateColaUI(Cola queue) {
        getQueuePanel().removeAll();
        Cola auxQueue = queue.cloneQueue();

        while (!auxQueue.isEmpty()) {
            Personaje character = auxQueue.dequeue();
            this.addCard(character.getUrlSource());
        }
        queuePanel.revalidate();
        queuePanel.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backgroundQueue = new javax.swing.JPanel();
        titleQueueUI = new javax.swing.JLabel();
        jScrollPaneQueue = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundQueue.setBackground(new java.awt.Color(204, 204, 204));
        backgroundQueue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleQueueUI.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        titleQueueUI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleQueueUI.setText("COLA PRIORIDAD:");
        backgroundQueue.add(titleQueueUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        jScrollPaneQueue.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPaneQueue.setForeground(new java.awt.Color(204, 204, 204));
        backgroundQueue.add(jScrollPaneQueue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 333, 105));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Tope de la cola");
        backgroundQueue.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 112, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Final de la cola");
        backgroundQueue.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 120, -1));

        jPanel1.add(backgroundQueue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColaUI().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundQueue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneQueue;
    private javax.swing.JLabel titleQueueUI;
    // End of variables declaration//GEN-END:variables
/**
     * @return the queuePanel
     */
    public JPanel getQueuePanel() {
        return queuePanel;
    }

    /**
     * @return the titleQueueUI
     */
    public javax.swing.JLabel getTitleQueueUI() {
        return titleQueueUI;
    }


}
