/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Extra.RenderImage;
import javax.swing.ImageIcon;
import proyecto2so.mainApp;


/**
 *
 * @author diego
 */
public class Home extends javax.swing.JFrame {

    private RenderImage imageUtils = new RenderImage();
   // private AudioManager audioManager;
    mainApp app = mainApp.getInstance();
    /**
     * Creates new form ColaUI
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        //Seteo del audioManager
        /*this.audioManager = new AudioManager(); 
        audioManager.playMusic("/GUI/Assets/backgroundSound.wav");
        */
        ImageIcon starWarsLogo = imageUtils.loadScaledImage("/GUI/Assets/StarWars/logo.png", 140, 80);
        ImageIcon starTrekLogo = imageUtils.loadScaledImage("/GUI/Assets/StarTrek/logo.png", 120, 80);
        
        moviePanelStarWars.getLogo().setIcon(starWarsLogo);
        moviePanelStarTrek.getLogo().setIcon(starTrekLogo);
        moviePanelStarWars.getLogo().setText("");
        moviePanelStarTrek.getLogo().setText("");
        iaStatusLabel.setText("");
        WinnerLabelID.setText("");

        // Se setean las imagenes que la lucha en la IA.
//        OJOOO LO BORRE

        // Se configura el slider 
        battleDuration.setOpaque(false);
        battleDuration.setMinimum(1);
        battleDuration.setMaximum(20);
        battleDuration.setValue(mainApp.getBattleDuration());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        moviePanelStarWars = new Interfaz.MoviePanelUI();
        moviePanelStarTrek = new Interfaz.MoviePanelUI();
        jPanel2 = new javax.swing.JPanel();
        roundLabel = new javax.swing.JLabel();
        iaStatusLabel = new javax.swing.JLabel();
        battleDuration = new javax.swing.JSlider();
        clockVelocity = new javax.swing.JLabel();
        WinnerLabelID = new javax.swing.JLabel();
        Winner1 = new javax.swing.JLabel();
        FightingTitle = new javax.swing.JLabel();
        starTrekFighter = new Interfaz.FighterUI();
        starWarsFighter = new Interfaz.FighterUI();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(moviePanelStarWars, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.add(moviePanelStarTrek, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        roundLabel.setForeground(new java.awt.Color(255, 255, 255));
        roundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roundLabel.setText("Round: 0");
        jPanel2.add(roundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 320, -1));

        iaStatusLabel.setFont(new java.awt.Font("Montserrat", 1, 17)); // NOI18N
        iaStatusLabel.setForeground(new java.awt.Color(255, 204, 0));
        iaStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iaStatusLabel.setText("IA STATUS LABEL");
        iaStatusLabel.setToolTipText("");
        jPanel2.add(iaStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 385, 27));

        battleDuration.setForeground(new java.awt.Color(255, 255, 255));
        battleDuration.setMajorTickSpacing(9);
        battleDuration.setMaximum(20);
        battleDuration.setMinimum(1);
        battleDuration.setMinorTickSpacing(1);
        battleDuration.setPaintLabels(true);
        battleDuration.setPaintTicks(true);
        battleDuration.setToolTipText("Slider de Velocidad");
        battleDuration.setValue(10);
        battleDuration.setOpaque(true);
        battleDuration.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                battleDurationStateChanged(evt);
            }
        });
        battleDuration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                battleDurationMouseClicked(evt);
            }
        });
        jPanel2.add(battleDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 730, 320, 40));

        clockVelocity.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        clockVelocity.setForeground(new java.awt.Color(255, 255, 255));
        clockVelocity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clockVelocity.setText("AJUSTE LA VELOCIDAD ");
        jPanel2.add(clockVelocity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 780, 210, -1));

        WinnerLabelID.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        WinnerLabelID.setForeground(new java.awt.Color(255, 204, 0));
        WinnerLabelID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WinnerLabelID.setText("Ganador");
        jPanel2.add(WinnerLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 700, 370, -1));

        Winner1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        Winner1.setForeground(new java.awt.Color(255, 204, 0));
        Winner1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Winner1.setText("GANADOR:");
        jPanel2.add(Winner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 670, 370, -1));

        FightingTitle.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        FightingTitle.setForeground(new java.awt.Color(255, 255, 255));
        FightingTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FightingTitle.setText("FIGHTING ARENA");
        jPanel2.add(FightingTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 390, -1));
        jPanel2.add(starTrekFighter, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));
        jPanel2.add(starWarsFighter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 560, 800));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void battleDurationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_battleDurationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_battleDurationMouseClicked

    private void battleDurationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_battleDurationStateChanged
        // TODO add your handling code here:
        int newSpeed = getBattleDuration().getValue();
        //        app.getIaArena().setCombatSpeed(newSpeed);
    }//GEN-LAST:event_battleDurationStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FightingTitle;
    private javax.swing.JLabel Winner1;
    private javax.swing.JLabel WinnerLabelID;
    private javax.swing.JSlider battleDuration;
    private javax.swing.JLabel clockVelocity;
    private javax.swing.JLabel iaStatusLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private Interfaz.MoviePanelUI moviePanelStarTrek;
    private Interfaz.MoviePanelUI moviePanelStarWars;
    private javax.swing.JLabel roundLabel;
    private Interfaz.FighterUI starTrekFighter;
    private Interfaz.FighterUI starWarsFighter;
    // End of variables declaration//GEN-END:variables

    public Interfaz.MoviePanelUI getmoviePanelStarWars() {
        return moviePanelStarWars;
    }

    /**
     * @return the tvPanelUI2
     */
    public Interfaz.MoviePanelUI getmoviePanelStarTrek() {
        return moviePanelStarTrek;
    }

    /**
     * @return the avatarFighter
     */
    public Interfaz.FighterUI getStarWarsFighter() {
        return starWarsFighter;
    }

    /**
     * @return the regularShowFighter
     */
    public Interfaz.FighterUI getStarTrekFighter() {
        return starTrekFighter;
    }

    /**
     * @return the iaStatusLabel
     */
    public javax.swing.JLabel getIaStatusLabel() {
        return iaStatusLabel;
    }

    /**
     * @return the WinnerLabelID
     */
    public javax.swing.JLabel getWinnerLabelID() {
        return WinnerLabelID;
    }

    /**
     * @return the roundLabel
     */
    public javax.swing.JLabel getRoundLabel() {
        return roundLabel;
    }

    /**
     * @return the battleDuration
     */
    public javax.swing.JSlider getBattleDuration() {
        return battleDuration;
    }

}
