/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import EstructuraDatos.Cola;
import javax.swing.JLabel;

/**
 *
 * @author diego
 */
public class MoviePanelUI extends javax.swing.JPanel {

    /**
     * Creates new form MoviePanelUI
     */
    public MoviePanelUI() {
        initComponents();
        this.getColaUI1().getTitleColaUI().setText("COLA DE PRIORIDAD: 1");
        this.getColaUI2().getTitleColaUI().setText("COLA DE PRIORIDAD: 2");
        this.getColaUI3().getTitleColaUI().setText("COLA DE PRIORIDAD: 3");
        this.getColaUI4().getTitleColaUI().setText("COLA DE REFUERZOS");
    }
    
    public void updateUICola(Cola queue1, Cola queue2, Cola queue3, Cola queue4) {
        this.colaUI1.updateColaUI(queue1);
        this.colaUI2.updateColaUI(queue2);
        this.colaUI3.updateColaUI(queue3);
        this.colaUI4.updateColaUI   (queue4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        victoriesLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        colaUI1 = new Interfaz.ColaUI();
        colaUI2 = new Interfaz.ColaUI();
        colaUI3 = new Interfaz.ColaUI();
        colaUI4 = new Interfaz.ColaUI();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setText("TVLogo");
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 100));

        victoriesLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        victoriesLabel.setForeground(new java.awt.Color(0, 204, 0));
        victoriesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        victoriesLabel.setText("0");
        jPanel2.add(victoriesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 150, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VICTORIAS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 150, -1));
        jPanel2.add(colaUI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel2.add(colaUI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        jPanel2.add(colaUI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));
        jPanel2.add(colaUI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 740));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Interfaz.ColaUI colaUI1;
    private Interfaz.ColaUI colaUI2;
    private Interfaz.ColaUI colaUI3;
    private Interfaz.ColaUI colaUI4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel victoriesLabel;
    // End of variables declaration//GEN-END:variables
    public JLabel getLogo() {
        return this.logo;
    }

    public ColaUI getColaUI1() {
        return this.colaUI1;
    }

    public ColaUI getColaUI2() {
        return this.colaUI2;
    }

    public ColaUI getColaUI3() {
        return this.colaUI3;
    }

    public ColaUI getColaUI4() {
        return this.colaUI4;
    }

    /**
     * @return the victoriesLabel
     */
    public javax.swing.JLabel getVictoriesLabel() {
        return victoriesLabel;
    }

}
